### ISSUE TITLE
1.1. StartupProfile

### ISSUE THREAD

**Issue by coffeeisknowledge** [OpenSource-DeltaTech-SW57/Informe-de-Proyecto#1]
1.1.1. Descripción de la Startup
1.1.2. Perfiles de integrantes del equipo

**Comment by JulioElsnerDLTU** [comment]
En esta etapa estoy empezando a redactar lo que vendría a ser nuestro Startup y sus características, ademas de crear una estructura para que cada uno de los integrantes suba su foto y redacte una breve descripción sobre ellos. 



![Image](https://github.com/OpenSource-DeltaTech-SW57/Informe-de-Proyecto/assets/111522511/5526d3e9-5364-4396-9f1a-b47d1fe56c96)



![Image](https://github.com/OpenSource-DeltaTech-SW57/Informe-de-Proyecto/assets/111522511/4042f0fa-d33a-48e0-9588-35a7bb867b29)

**Comment by JulioElsnerDLTU** [comment]
Ya habiendo redactado todos los puntos que abarca nuestro Startup de manera concisa y directa, teniendo en cuenta la rubrica pude dar por finalizado este issue.
