### ISSUE TITLE
1.3. Segmentos Objetivos

### ISSUE THREAD

**Issue by coffeeisknowledge** [OpenSource-DeltaTech-SW57/Informe-de-Proyecto#4]
Actividad grupal para debatir sobre los segmentos finales de nuestra web application.

**Comment by JulioElsnerDLTU** [comment]
Se definen los segmentos objetivos proyectados en nuestro producto "DiligenceTech" y es discutido por los integrantes del grupo.

**Comment by JulioElsnerDLTU** [comment]
Ya que hallamos discutido y especificado definitivamente los dos segmentos objetivos se llenan todos los datos de cada uno de ellos.

![Image](https://github.com/OpenSource-DeltaTech-SW57/Informe-de-Proyecto/assets/111522511/b554f0bb-681e-4dd2-ac0c-81d72a5e7873)

![Image](https://github.com/OpenSource-DeltaTech-SW57/Informe-de-Proyecto/assets/111522511/af083322-ddb4-47d0-9b6f-7d9b6b6c7730)

**Comment by JulioElsnerDLTU** [comment]
Mediante la colaboración en grupo realizamos unos últimos cambios y se finaliza este procedimiento.
