### ISSUE TITLE
2.1. Competidores

### ISSUE THREAD

**Issue by coffeeisknowledge** [OpenSource-DeltaTech-SW57/Informe-de-Proyecto#5]
2.1.1. Análisis competitivo.
2.1.2. Estrategias y tácticas frente a competidores.

**Comment by LuisHerreraG** [comment]
Se investiga los competidores directos e indirectos que pueda tener nuestra solución de Due Diligence, tomando en cuenta que a estos tipos de software de servicio de alojamiento especializado se les conoce como Virtual Data Rooms.

**Comment by LuisHerreraG** [comment]
Se ha optado por comparar nuestra solución Due Diligence a las 3 alternativas más populares del mundo. Siendo la top 1 también reconocida en nuestro país:

![Image](https://github.com/OpenSource-DeltaTech-SW57/Informe-de-Proyecto/assets/165408949/99e5e26e-2992-4cc8-98b9-ac6ac286b03e)

**Comment by LuisHerreraG** [comment]
Se agregó información de los competidores, como segmentos objetivos se ha copiado los mismos de Datasite Diligence para todos hasta posteriormente ser reemplazados. Además se hizo el análisis competitivo y sus estrategias consecuentes. No obstante, no se ha publicado el análisis todavía a causa de tener que insertarlo como imagen.


![Image](https://github.com/OpenSource-DeltaTech-SW57/Informe-de-Proyecto/assets/165408949/7b6ca373-2e00-44c7-9462-88a96821d12a)



![Image](https://github.com/OpenSource-DeltaTech-SW57/Informe-de-Proyecto/assets/165408949/36fe2fc7-a528-4d8a-afaa-c26fd69d0d68)



![Image](https://github.com/OpenSource-DeltaTech-SW57/Informe-de-Proyecto/assets/165408949/e0ea2321-6a50-4aa3-b217-9bca3ba8b53c)



![Image](https://github.com/OpenSource-DeltaTech-SW57/Informe-de-Proyecto/assets/165408949/ab0aef3b-bc8b-4366-88f4-7dd70347eb92)



![Image](https://github.com/OpenSource-DeltaTech-SW57/Informe-de-Proyecto/assets/165408949/20e11272-cc42-4d7a-8652-8045e32eb533)



![Image](https://github.com/OpenSource-DeltaTech-SW57/Informe-de-Proyecto/assets/165408949/3b1f20d1-c647-4f08-ac2e-cd8b3aea12a4)
