### ISSUE TITLE
2.3. Needfinding

### ISSUE THREAD

**Issue by coffeeisknowledge** [OpenSource-DeltaTech-SW57/Informe-de-Proyecto#7]
2.3.1. User Personas.
2.3.2. User Task Matrix.
2.3.3. User Journey Mapping.
2.3.4. Empathy Mapping.
2.3.5. As-is Scenario Mapping.

**Comment by OscarGarayar** [comment]
Se iniciará el proceso de Needfinding

**Comment by OscarGarayar** [comment]
Con respecto al As Is scenario se ha comenzado el planteamiento de las etapas que llevará el usuario

**Comment by OscarGarayar** [comment]
Se ha completado el As Is scenario map para el usuario inversionista

**Comment by OscarGarayar** [comment]
![Image](https://github.com/OpenSource-DeltaTech-SW57/Informe-de-Proyecto/assets/102541011/eb964a25-9a48-4176-936d-dea9fef6e72f)

**Comment by OscarGarayar** [comment]
Se ha implementado el As Is scenario map para el usuario contador financiero

![Image](https://github.com/OpenSource-DeltaTech-SW57/Informe-de-Proyecto/assets/102541011/f878c911-c7b7-41e0-99b0-298eb414712e)
