### ISSUE TITLE
Requirements Specification

### ISSUE THREAD

**Issue by coffeeisknowledge** [OpenSource-DeltaTech-SW57/Informe-de-Proyecto#9]
3.1. To-Be Scenario Mapping.
3.2. User Stories.
3.3. Impact Mapping.
3.4. Product Backlog.

**Comment by OscarGarayar** [comment]
Se comenzará con el desarrollo de esta sección, se discutirá los requerimientos necesarios para el funcionamiento de la aplicación

**Comment by OscarGarayar** [comment]
Se están desarrollando los user stories para los usuarios inversionistas, se está consultando con el grupo sus opiniones y si se debería de corregir los ya realizados.

**Comment by OscarGarayar** [comment]
![Image](https://github.com/OpenSource-DeltaTech-SW57/Informe-de-Proyecto/assets/102541011/ee8c9605-404e-4d41-806e-1b0fb9de1dcc)

**Comment by OscarGarayar** [comment]
Por el momento se están agrupando en base a las etapas que realizará el usuario dentro de la app

**Comment by OscarGarayar** [comment]
Se ha comenzado con la creación de user stories para el usuario contador financiero

**Comment by OscarGarayar** [comment]
![Image](https://github.com/OpenSource-DeltaTech-SW57/Informe-de-Proyecto/assets/102541011/6d66ac8d-94f4-4d4e-a73d-6e7ac3fe835f)

**Comment by OscarGarayar** [comment]
Se ha creado y asignado el primer epic para los user stories



![Image](https://github.com/OpenSource-DeltaTech-SW57/Informe-de-Proyecto/assets/102541011/3f875007-8852-41a8-b4a5-8da59da74073)

**Comment by OscarGarayar** [comment]
Se crearon y asignaron los demás epics

![Image](https://github.com/OpenSource-DeltaTech-SW57/Informe-de-Proyecto/assets/102541011/4d13dfdb-367d-4d92-8fef-d13719657184)

**Comment by OscarGarayar** [comment]
Se están creando los criterios de aceptación



![Image](https://github.com/OpenSource-DeltaTech-SW57/Informe-de-Proyecto/assets/102541011/ba6de640-079b-4ab1-855c-cb2f37456a4f)

**Comment by OscarGarayar** [comment]
se implemento el impact map y el product backlog

**Comment by OscarGarayar** [comment]
![Image](https://github.com/OpenSource-DeltaTech-SW57/Informe-de-Proyecto/assets/102541011/d281d065-a089-45a4-b10d-b14bd1f8a1eb)

**Comment by OscarGarayar** [comment]
![Image](https://github.com/OpenSource-DeltaTech-SW57/Informe-de-Proyecto/assets/102541011/b2f9a839-bc27-461d-bf18-8b3261b7a33d)
